### ISSUE TITLE
[Bug]: Backlight Controller code fail to compile.

### ISSUE THREAD

**Issue by Benny927** [jrsteensen/OpenHornet-Software#164]
### Discord Username

Murtle

### Bug Summary

The Backlight controller code fails to compile after updating fastled library from 3.10.3 to 3.10.4 on the Arduino IDE.

### Expected Results

The code should compile after updates to library with out fail.

### Actual Results

Errors from compile fails after updates to the fastled library.

### Applicable File Names

2A13-BACKLIGHT_CONTROLLER

### Release Version

v0.3.0

### Category

Libraries & Dependencies (Arduino Libraries, etc)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Hardware is built to print & this software is tested on that hardware?

- [ ] I built (or attempted to build) the part to the OpenHornet print without any deviations and tested the software on it.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by eHanseJoerg** [comment]
Bug is confirmed. 
Since 3.10.4, FastLEDs src/platforms/avr/io_avr.cpp.hpp includes platforms/arduino/io_arduino.hpp, whose fl::platforms::begin/print/available/read are implemented on the Arduino Serial object. Because the AVR unity build (platforms/avr/_build.cpp.hpp) always compiles this TU, every AVR build now carries a hard reference to Serial. 
DCS-Bios tries to define its own ISR(USART0_RX_vect), which results in a conflict:

```
HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_25'
sketch/MySketch.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```
Temporary solution: use FastLED library 3.10.3

Final solutions investigated:

1. **Using 3.10.5 + DCS-Bios default serial:** Set FASTLED_ALLOW_INTERRUPTS 1 and drop the manual cli()/sei(). Allow DCS-Bios default serial updates while FastLED.show() update is running
**Rejected**, because any interrupt in FastLED.show() update cycle may cause a restart from index 0, resulting in wrong indicators lighting up. We would trade correctness for speed, and we would make debugging virtually impossible

2. **Using 3.10.5 + DCS-Bios default serial:** Show one channel per loop iteration instead of all ten in one FastLED.show(), shrinking the worst-case blackout from ~51 ms to ~10.5 ms (LED RC_2). Reduces the loss of bytes incoming from DCS-Bios, as FastLED.show() updates now are shorter. Disadvantage: the maxPower() calculations are assuming FastLED.show() updates ALL LEDs, which is not happening here, so we would trade safety for speed

3. **Using 3.10.3 + DCS-Bios IRQ serial:** ensures FastLED update correctness, but DCS-Bios incoming bytes may still be lost. However, DCS-Bios has an auto-sweep function that sends current state every few seconds so the maximum delay would be about 3.5 seconds 

Option 3 is currently implemented, with an optimization of timing in  https://github.com/jrsteensen/OpenHornet-Software/pull/165 .
